### ISSUE TITLE
Annotation of "plus de"

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/UD_French-Sequoia#1]
While looking at the annotation of "plus de" in the Sequoia corpus I found it tagged in a couple of different ways. Do these look like the same thing, should they be tagged the same ?

```
# sent_id = emea-fr-dev_00039
# text = Angiox a été étudié chez plus de 20 000 patients.
1       Angiox  Angiox  PROPN   _       _       4       nsubj:pass      _       _
2       a       avoir   AUX     _       Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   4       aux     _       _
3       été     être    AUX     _       Tense=Past|VerbForm=Part        4       aux:pass        _       _
4       étudié  étudier VERB    _       Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part|Voice=Pass     0       root    _       _
5       chez    chez    ADP     _       _       9       case    _       _
6       plus    plus    ADV     _       _       9       advmod  _       _
7       de      de      ADP     _       _       9       dep     _       _
8       20 000  20 000  DET     _       _       9       det     _       _
9       patients        patient NOUN    _       Gender=Masc|Number=Plur 4       obl     _       SpaceAfter=No
10      .       .       PUNCT   _       _       4       punct   _       _
```

```
# sent_id = annodis.er_00086
# text = Cela fait donc plus de trois-quarts de siècle que la digne société du même nom encourage, dans la région, les éleveurs amateurs.
1       Cela    cela    PRON    _       Number=Sing|PronType=Dem        2       nsubj   _       _
2       fait    faire   VERB    _       Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0       root    _       _
3       donc    donc    ADV     _       _       2       advmod  _       _
4       plus    plus    ADV     _       _       6       det     _       _
5       de      de      ADP     _       _       4       fixed   _       _
6       trois-quarts    trois-quarts    NOUN    _       Gender=Masc|Number=Sing 2       obl     _       _
7       de      de      ADP     _       _       8       case    _       _
8       siècle  siècle  NOUN    _       Gender=Masc|Number=Sing 6       nmod    _       _
```

Here are the counts:

     24 	plus|ADV|advmod	de|ADP|dep	
      8 	plus|ADV|det	de|ADP|fixed	
      1 	plus|ADV|fixed	de|ADP|mark

**Comment by dan-zeman** [comment]
The emea-fr-dev_00039 annotation seems wrong/suboptimal just because it employs the `dep` relation. Joining _plus de_ with the `fixed` relation seems OK as an analogy to _more than_, which is analyzed this way in English (http://universaldependencies.org/u/overview/specific-syntax.html#more-than-as-a-multi-word-expression).

**Comment by perrier54** [comment]
I agree with Dan. In the expression "plus de " + NUM + NOUN, "plus de" must be annotated as "more than" in English.  "plus de" is a fixed expression, which depends on NUM in an ADVMOD dependency.
In  the expression "plus de" + NOUN (_il a plus de problèmes_), I believe that "plus de" is a fixed expression, which depends on NOUN in a DET dependency.

**Comment by bguil** [comment]
Fixed

**Comment by rafael75012** [comment]
Would "de plus"/"en plus" when they are postposed to the noun/pronoun they depend on, be ADV in an _advmod_ dependency?

> Je n'attend rien **de plus**
> Tu m'en feras une **en plus**
> Mille francs **de plus** à payer
