### ISSUE TITLE
acl "for secondary predicates modifying a nominal"

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/UD_French-Sequoia#3]
The French page of the UD guide for the acl relation mentions that acl "is also used for secondary predicates modifying a nominal", and gives the following example : 

> "Il--[quitta la pièce]--acl-->pleurant"

Would it be more accurate to analyze this kind of structure with xcomp? As we find this analysis in Sequoia :  

> "Guy était arrivé--xcomp-->tout jeune"

**Comment by rafael75012** [comment]
This problem seems to be linked to what has to be considered as "attribut du sujet" when the verb is not the copula _être_. In Sequoia we can find two different analysis, respectively : 

> Guy était arrivé--ats-->tout jeune
> elle vivait--mod-->seule

Which naturally leads to get two analysis in UD : 

> Guy était arrivé--xcomp-->tout jeune
> elle vivait--advmod-->seule

Plus the analysis mentioned in the comment above, we get three analysis for the same construction.

**Comment by sylvainkahane** [comment]
I think that `xcomp` should be kept for predicative arguments.
For:
```
Il quitta la pièce pleurant/en pleurant/en larmes
Guy était arrivé tout jeune/à trois ans
```
it is clearly a modifier and `acl` is probably the best solution.
For:
```
elle vivait seule/avec sa mère
```
we could postulate that it is an argument and choose `xcomp` rather than `acl`.

**Comment by rafael75012** [comment]
Ok, it may be useful that the indications appear in the UD guide, as "attribut du sujet/objet" are quite frequent constructions in French
